### ISSUE TITLE
Use tlsh with cmake, missing include "version.h"

### ISSUE THREAD

**Issue by adib0u** [trendmicro/tlsh#91] opened 2020-08-04 13:12 UTC
When I use the c++ library in my project and include it with `#include tlsh.h` then i have the following error :  
```
/usr/local/include/tlsh.h:66:10 fatal error: version.h: No file found
#include "version.h"
```
It seems like the file /usr/local/include/version.h doesn't exist.
It's generated when i run `make.sh` but is not installed when using `make install` in the `build/release` directory.
Am I doing something wrong during the installation ?

**Comment by jonjoliver** [comment] 2020-08-25 04:40
There is no need to install any .h files in /usr/local/include/

There is no need to go into build/release directory and do the command
$ make install

The binary "tlsh_unittest" in the bin directory is a stand-alone program

Should I add installation instructions?
all the installation instructions will say is to copy the binary to the directory where you want it...

**Comment by Dkapps** [comment] 2020-09-02 14:18
@jonjoliver Just giving my 2 cents here, but if we aren't supposed to install anything, I think we should either disable the `install` target or provide instructions on what exactly that target is for.  

As it stands, it is kind of confusing because `make install` is AFAIK generally used to install libraries in `/usr/local/lib` + `/usr/local/include` (to allow for standardised library includes in build systems), or install programs in `/usr/local/bin` (or both, of course)

**Comment by jonjoliver** [comment] 2020-12-17 23:54
@Dkapps I agree. That is a historical accident. I don't want to break other projects that use tlsh as a library.
What is the safest way forwards here - that minimizes the impact on dependent projects.

**Comment by juju4** [comment] 2021-06-12 13:00
It seems problem is still current and appearing on centos8 as it does in my tlsh ansible role
https://github.com/juju4/ansible-tlsh/runs/2809688106?check_suite_focus=true#step:6:376

any fix/workaround?

Thanks

**Comment by Dkapps** [comment] 2021-06-12 15:57
@jonjoliver I opened the PR #103 to propose a fix for this situation.   
Like I said in the description of the PR, if we do not want to remove the `make install` target, we might as well fix it so that it works as intended

Let me know if this works for you

**Closed** 2021-09-08 08:48 UTC
